dubbo:
  cloud:
    subscribed-services: spring-cloud-nacos-sample
  scan:
    base-packages: com.example

spring:
  application:
    name: spring-cloud-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.111:8848,192.168.6.112:8848,192.168.6.113:8848