dubbo:
  cloud:
    subscribed-services: spring-cloud-dubbo-sample

spring:
  application:
    name: spring-cloud-dubbo-sample-consumer

  cloud:
    zookeeper:
      discovery:
        register: false
#      connect-string: 121.36.5.129:2181
      connect-string: 192.168.6.110:2181