dubbo:
  protocol:
    port: 20880
    name: dubbo
#  application:
#    name: spring-cloud-dubbo-sample-provider

spring:
  application:
    name: spring-cloud-dubbo-sample
  cloud:
    zookeeper:
      discovery:
        register: true
#      connect-string: 121.36.5.129:2181
      connect-string: 192.168.6.110:2181